---

rules:
  anchors: enable
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
  brackets: enable
  colons: enable
  commas: enable
  comments: enable
  comments-indentation: enable
  document-start: enable
  empty-lines:
    max: 1
  empty-values: enable
  float-values:
    forbid-inf: true
    forbid-nan: true
    forbid-scientific-notation: true
    require-numeral-before-decimal: true
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: true
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  octal-values: enable
  quoted-strings:
    quote-type: double                  
    required: only-when-needed          
    extra-required:                     
      - '\{\{.*\}\}'                   
      - '^[0-9]+\.[0-9]+$'             
      - '^[0-9]+(:[0-9]+)+$'           
      - '^0[0-9]+$'                     
    extra-allowed:
      - '^\{.*\}$'               
    allow-quoted-quotes: true           
    check-keys: false                 
  truthy: enable
  trailing-spaces: enable
