---

rules:
  anchors: enabled
  braces: enabled
  brackets: enabled
  colons: enabled
  commas: enabled
  comments: enabled
  comments-indentation: enabled
  document-start: enabled
  empty-lines:
    max: 1
  empty-values: enabled
  float-values:
    forbid-inf: true
    forbid-nan: true
    forbid-scientific-notation: true
    require-numeral-before-decimal: true
  hyphens: enabled
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: true
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  octal-values: enabled
  quoted-strings:
    quote-type: double                  
    required: only-when-needed          
    extra-required:                     
      - '\{\{.*\}\}'                   
      - '^[0-9]+\.[0-9]+$'             
      - '^[0-9]+(:[0-9]+)+$'           
      - '^0[0-9]+$'                     
    extra-allowed: []                   
    allow-quoted-quotes: true           
    check-keys: true                    
  truthy: enabled
